# @package _global_

defaults:
  # ===================================================================================
  # OVERRIDE
  # ===================================================================================
  - _self_

  # ===================================================================================
  # CORE - core things for the project such as paths, hydra behaviour, logger etc
  # ===================================================================================
  - core: default
  - hydra: default
  - paths: default
  - logger: null

  # ===================================================================================
  # EXTRAS
  # ===================================================================================
  - extras: default

  # ===================================================================================
  # DATASET - dataset related config
  # ===================================================================================
  - datamodule: mnist

  # ===================================================================================
  # MODEL - model related configs
  # ===================================================================================
  - model: mnist
  - lightning_model: mnist

  # ===================================================================================
  # training related
  # ===================================================================================
  - trainer: default
  - callbacks: null 

task_name: "eval"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
checkpoint_path: ???
